spring.application.name=bank40back

# PostgreSQL
# P6Spy - settings
spring.datasource.url=jdbc:p6spy:postgresql://localhost/postgres
spring.datasource.driverClassName=com.p6spy.engine.spy.P6SpyDriver

# normal settings
#spring.datasource.driverClassName=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost/postgres
spring.datasource.username=postgres
spring.datasource.password=student123

# JPA stuff
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Enable SQL initialization
spring.sql.init.mode=always

# Disable Hibernate DDL generation to avoid conflicts
spring.jpa.hibernate.ddl-auto=none